name: release
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [ 21 ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: datagen
        run: ./gradlew runDatagen
      - name: build
        run: ./gradlew build


      - name: Get Mod Version
        id: mod_version
        run: grep "mod_version" gradle.properties | sed "s/\s//g" >> $GITHUB_OUTPUT


      - name: release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.PAT }}"
          tag_name: "${{ steps.mod_version.outputs.mod_version }}"
          name: "Crystallised ${{ steps.mod_version.outputs.mod_version }}"
          prerelease: false
          files: build/libs/crystallised-${{ steps.mod_version.outputs.mod_version }}.jar
