name: release
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [ 21 ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: datagen
        run: ./gradlew runDatagen
      - name: build
        run: ./gradlew build
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.PAT }}"
          tag_name: "${{ github.run_number }}"
          name: "Crystallised ${{ github.run_number }}"
          prerelease: false
          files: build/libs/crystallised-[0-9]+\.[0-9]+\.[0-9]+\.jar
